Imports
```{r}

# 0) (Re)start R so nothing Python‐side has already been loaded.

# 1) Force the exact Python you want
Sys.setenv(
  RETICULATE_PYTHON = "/Users/fkampf/Library/r-miniconda-arm64/envs/r-reticulate/bin/python"
)

# 2) Load the R arrow package first (registers “file://” handler)
library(arrow)

# 3) Now bind reticulate → your conda env
library(reticulate)
use_condaenv(
  "/Users/fkampf/Library/r-miniconda-arm64/envs/r-reticulate",
  required = TRUE
)

# 4) Import pyarrow.fs (v18.x will ignore the already-registered “file” scheme)
py_run_string("import pyarrow.fs")

# 5) All your neuroscience + tidyverse packages
library(malecns)
library(coconatfly)
library(fafbseg)
library(neuprintr)

library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(stringr)
library(igraph)
library(tidygraph)
library(ggraph)
library(jsonlite)
library(reshape2)
library(Matrix)
library(bit64)


# 6) (Optional) neuprint login / quick test
conna = neuprint_login(dataset='male-cns:v0.9',
                       server='https://neuprint-cns.janelia.org/')
mcns.rois = neuprint_ROIs(dataset = 'male-cns:v0.9')
py_run_string("import pyarrow; print('pyarrow v'+pyarrow.__version__)")


```

```{r setup, include=FALSE}
# Setup knitr global options for clean rendering and consistent figures
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.align = 'center',
  fig.width = 8,
  fig.height = 6
)
```


## 1 Load data

### 1.1 Load body annotations
```{r}
synapse_threshold=5
mba<-mcns_body_annotations()
mba.static<-mba
mba<-mba%>%mutate(type=ifelse(type=='',NA,type))
mba <- mba %>%
  mutate(type=coalesce(type,flywire_type,manc_type,hemibrain_type))%>%
  mutate(cachero.type = str_extract(synonyms, "(?<=Cachero 2010:)[^;]+") %>%
                            str_trim())


flytable<-flytable_query("select * from info")

```

### 1.2 Function to load connectivity
```{r}
fetch.connectivity.fw <- function(flytable = NULL, synapse_threshold = 5) {
  if (is.null(flytable)) {
    flytable <- flytable_query("select * from info")
  }

  fw.ids <- flytable %>%
    pull(root_id) %>%
    unique()

  connectivity <- cf_partners(
      cf_ids(flywire = fw.ids),
      partners  = "o",
      threshold = synapse_threshold
    ) %>%
    select(pre_id, post_id, weight)

  # helper to build a lookup table
  annotate <- flytable %>%
    select(
      root_id,
      cell_type,
      fru_dsx,
      top_nt,
      malecns_type,
      hemibrain_type
    ) %>%
    mutate(root_id = as.integer64(root_id))

  connectivity %>%
    # pre side
    left_join(
      annotate %>%
        rename(
          pre_id          = root_id,
          pre_type        = cell_type,
          pre_fru_dsx     = fru_dsx,
          pre_nt          = top_nt,
          pre_mcns_type   = malecns_type,
          pre_hemibrain_type = hemibrain_type
        ),
      by = "pre_id"
    ) %>%
    # post side
    left_join(
      annotate %>%
        rename(
          post_id         = root_id,
          post_type       = cell_type,
          post_fru_dsx    = fru_dsx,
          post_nt         = top_nt,
          post_mcns_type  = malecns_type,
          post_hemibrain_type = hemibrain_type
        ),
      by = "post_id"
    ) %>%
    # final column order, no duplicates
    select(
      weight,
      pre_id, post_id,
      pre_type, post_type,
      pre_mcns_type, post_mcns_type,
      pre_hemibrain_type, post_hemibrain_type,
      pre_fru_dsx, post_fru_dsx,
      pre_nt, post_nt
    )
}

```

### 1.3 Load connectivity
```{r}
conn <-fetch.connectivity.fw(flytable)
conn_save <- conn



```

## 2 Adjacency matrix
### 2.1 Function adjacency matrix
```{r}
calculate_normed_adj_matrix <-function(connectivity,cell.or.type='type',pre.or.post='pre'){
  colScale <- function(A, na.rm = TRUE) {
    scalefac <- 1 / Matrix::colSums(A)
    if (na.rm) scalefac[!is.finite(scalefac)] <- 0
    B <- A %*% Matrix::Diagonal(x = scalefac)
    B
    }
  rowScale <- function(A, na.rm = TRUE) {
    scalefac <- 1 / Matrix::rowSums(A)
    if (na.rm) scalefac[!is.finite(scalefac)] <- 0
    B <- Matrix::Diagonal(x = scalefac) %*% A
    B
    }
  if(cell.or.type=='cell'){
    unique.identifier <- union(as.character(connectivity$pre_id), as.character(connectivity$post_id))
    adj.matrix <- sparseMatrix(
      i = match(connectivity$pre_id, unique.identifier),
      j = match(connectivity$post_id, unique.identifier),
      x = connectivity$weight,
      dims = c(length(unique.identifier), length(unique.identifier)),
      dimnames = list(unique.identifier, unique.identifier))
  }else{
    unique.identifier <- union(connectivity$pre_type, connectivity$post_type)
    adj.matrix <- sparseMatrix(
      i = match(connectivity$pre_type, unique.identifier),
      j = match(connectivity$post_type, unique.identifier),
      x = connectivity$weight,
      dims = c(length(unique.identifier), length(unique.identifier)),
      dimnames = list(unique.identifier, unique.identifier))
  }
  if(pre.or.post=='pre'){
    adj.matrix.normed.pre <- rowScale(adj.matrix)
    colnames(adj.matrix.normed.pre) <- colnames(adj.matrix)
    rownames(adj.matrix.normed.pre) <- rownames(adj.matrix)
    return(adj.matrix.normed.pre)
  }else if(pre.or.post=='avg'){
    adj.matrix.normed.post <- colScale(adj.matrix)
    colnames(adj.matrix.normed.post) <- colnames(adj.matrix)
    rownames(adj.matrix.normed.post) <- rownames(adj.matrix)
    adj.matrix.normed.pre <- rowScale(adj.matrix)
    colnames(adj.matrix.normed.pre) <- colnames(adj.matrix)
    rownames(adj.matrix.normed.pre) <- rownames(adj.matrix)
    
    return(avg_mat <- (adj.matrix.normed.post + adj.matrix.normed.post) / 2)
    
  }
  
  else{
    adj.matrix.normed.post <- colScale(adj.matrix)
    colnames(adj.matrix.normed.post) <- colnames(adj.matrix)
    rownames(adj.matrix.normed.post) <- rownames(adj.matrix)
    return(adj.matrix.normed.post)
  }
}
```

load schlegel matching
```{r}
load.schlegel.matching <- function(path="/Users/fkampf/mappings.json"){
schlegel.matching <- fromJSON("/Users/fkampf/mappings.json")
schlegel.matching.df <- data.frame(schlegel.matching)


library(tidyr)
library(dplyr)

schlegel.matching.df.formatted <- schlegel.matching.df %>%
  pivot_longer(
    cols = matches("^(FlyWire|MaleCNS)\\."),
    names_to = "ID",
    values_to = "Label"
  ) %>%
  mutate(
    Dataset = case_when(
      str_starts(ID, "FlyWire") ~ "fw",
      str_starts(ID, "MaleCNS") ~ "mcns",
      TRUE ~ "Other"
    ),
    ID = str_remove(ID, "^(FlyWire|MaleCNS)\\.")
  )%>%
  rename(bodyid=ID,type=Label,dataset=Dataset)
return(schlegel.matching.df.formatted)
}
schlegel.matching<-load.schlegel.matching()%>%filter(dataset=='fw')
```


Get aPN1, vPN1, JO-B, vpoEN, vpoIN, and all other via schlegel matching and mcns
```{r}
majority_vote <- function(x) {
  x <- na.omit(x)
  if (length(x) == 0) return(NA)
  tab <- table(x)
  top <- which.max(tab)
  names(tab)[top]
}

protected<-c('aPN1','aPN1_like','vpoIN','vpoEN')

vPN1.ids  <- mba %>% filter(str_detect(synonyms, 'vPN1')) %>% pull(bodyid)
aPN1.ids  <- mba %>% filter(str_detect(synonyms, 'aPN1')) %>% pull(bodyid)
vpoEN.ids <- mba %>% filter(str_detect(type, 'vpoEN'))    %>% pull(bodyid)
vpoIN.ids <- mba %>% filter(str_detect(type, 'vpoIN'))    %>% pull(bodyid)
pIP10.ids <- mba %>% filter(str_detect(type, 'pIP10'))    %>% pull(bodyid)
pMP2.ids  <- mba %>% filter(str_detect(type, 'pMP2'))     %>% pull(bodyid)

aPN1.types <- mba %>% filter(bodyid %in% aPN1.ids,!is.na(type)) %>% pull(type) %>% unique()
aPN1.groups <- mba %>% filter(bodyid %in% aPN1.ids) %>% pull(group) %>% unique()
aPN1_like.ids <- mba %>% filter(type %in% aPN1.types | group %in% aPN1.groups) %>% filter(!str_detect(synonyms, 'aPN1')) %>% pull(bodyid)

mba.mod <- mba %>%
  mutate(
    type = case_when(
      bodyid %in% vPN1.ids ~ 'vPN1',
      bodyid %in% aPN1.ids ~ 'aPN1',
      bodyid %in% aPN1_like.ids ~ 'aPN1_like',
      bodyid %in% vpoEN.ids ~ 'vpoEN',
      bodyid %in% vpoIN.ids ~ 'vpoIN',
      bodyid %in% pIP10.ids ~ 'pIP10',
      bodyid %in% pMP2.ids ~ 'pMP2',
      TRUE ~ type
    )
  )


mba.per.fw.type <- mba.mod %>%
  group_by(flywire_type) %>%
  summarise(
    bodyid = majority_vote(bodyid),
    fru_dsx = majority_vote(fru_dsx),
    consensus_nt = majority_vote(consensus_nt),
    flywire_type = majority_vote(flywire_type),
    synonyms = majority_vote(synonyms),
    receptor_type = majority_vote(receptor_type),
    cachero.type = majority_vote(cachero.type),
    mcns.type2 = majority_vote(type),
    .groups = "drop"
  )%>%
  filter(!is.na(flywire_type))


conn <- conn_save %>%
  left_join(mba.per.fw.type%>%
              select(flywire_type,
                     synonyms,
                     cachero.type,
                     mcns.type2)%>%
              rename(pre_type=flywire_type,
                     pre_synonyms=synonyms,
                     pre_cachero.type=cachero.type,
                     pre_mcns.type2 = mcns.type2),
            by='pre_type')%>%
  left_join(mba.per.fw.type%>%
              select(flywire_type,
                     synonyms,
                     cachero.type,
                     mcns.type2)%>%
              rename(post_type=flywire_type,
                     post_synonyms=synonyms,
                     post_cachero.type=cachero.type,
                     post_mcns.type2 = mcns.type2),
            by='post_type')

```




```{r}
#Try to get the correct cell types post and pre
#conn.types <- 
selected.columns <- colnames(conn)[
  (grepl('pre', colnames(conn)) | grepl('post', colnames(conn))) &
    grepl('type', colnames(conn))]

selected.columns.pre <- selected.columns[grepl('pre',selected.columns)]
selected.columns.post <- selected.columns[grepl('post',selected.columns)]
```


### 2.1 Create adjacency matrix
```{r}
conn_work <- conn
list.exception <- c('aPN1','aPN1_like','pMP2','pIP10','aSP-k','vpoDN','JO-B','pIP-e','vPN1','vpoIN','vpoEN')
library(dplyr)
conn_work$pre_type_exception = NA
conn_work$post_type_exception = NA
for (exception in list.exception) {
  conn_work <- conn_work %>%
    mutate(pre_type = case_when(
      if_any(selected.columns.pre, ~ grepl(exception, .)) ~ exception,
      TRUE ~ pre_type_exception
    ),
    post_type_exception = case_when(
      if_any(selected.columns.post, ~ grepl(exception, .)) ~ exception,
      TRUE ~ post_type_exception
    ))
}




conn_work <- conn_work%>%
  mutate(pre_type=coalesce(pre_type_exception,
                           pre_cachero.type,
                           pre_mcns.type2,
                           pre_mcns_type,
                           pre_type,
                           pre_hemibrain_type),
         post_type=coalesce(post_type_exception,
                            post_cachero.type,
                            post_mcns.type2,
                            post_mcns_type,
                            post_type,
                            post_hemibrain_type))%>%
  mutate(pre_type=if_else(is.na(pre_type),
                          as.character(pre_id),
                          pre_type),
         post_type=if_else(is.na(post_type),
                           as.character(post_id),
                           post_type))%>%
  mutate(pre_type = gsub("[()]", "", pre_type))%>%
  mutate(post_type = gsub("[()]", "", post_type))


#rewrite types
vPN1.ids  <- mba %>% filter(str_detect(synonyms, 'vPN1')) %>% pull(bodyid)
aPN1.ids  <- mba %>% filter(str_detect(synonyms, 'aPN1')) %>% pull(bodyid)
vpoEN.ids <- mba %>% filter(str_detect(type, 'vpoEN'))    %>% pull(bodyid)
vpoIN.ids <- mba %>% filter(str_detect(type, 'vpoIN'))    %>% pull(bodyid)
pIP10.ids <- mba %>% filter(str_detect(type, 'pIP10'))    %>% pull(bodyid)
pMP2.ids  <- mba %>% filter(str_detect(type, 'pMP2'))     %>% pull(bodyid)
aPN1.types <- mba %>% filter(bodyid %in% aPN1.ids,!is.na(type)) %>% pull(type) %>% unique()
aPN1.groups <- mba %>% filter(bodyid %in% aPN1.ids) %>% pull(group) %>% unique()
aPN1_like.ids <- mba %>% filter(type %in% aPN1.types | group %in% aPN1.groups) %>% filter(!str_detect(synonyms, 'aPN1')) %>% pull(bodyid)
all.P1.type <- mba%>%filter(grepl('^P1_',type))%>%pull(type)%>%unique()
conn_work <- conn_work %>%
  mutate(
    pre_type = case_when(
      pre_id %in% vPN1.ids ~ 'vPN1',
      pre_id %in% aPN1.ids ~ 'aPN1',
      pre_id %in% aPN1_like.ids ~ 'aPN1_like',
      pre_id %in% vpoEN.ids ~ 'vpoEN',
      pre_id %in% vpoIN.ids ~ 'vpoIN',
      pre_id %in% pIP10.ids ~ 'pIP10',
      pre_id %in% pMP2.ids ~ 'pMP2',
      TRUE ~ pre_type
    ),
    post_type = case_when(
      post_id %in% vPN1.ids ~ 'vPN1',
      post_id %in% aPN1.ids ~ 'aPN1',
      post_id %in% aPN1_like.ids ~ 'aPN1_like',
      post_id %in% vpoEN.ids ~ 'vpoEN',
      post_id %in% vpoIN.ids ~ 'vpoIN',
      post_id %in% pIP10.ids ~ 'pIP10',
      post_id %in% pMP2.ids ~ 'pMP2',
      TRUE ~ post_type
    )
  ) %>%
  mutate(
    pre_type = case_when(
      !pre_type %in% c('vPN1','aPN1','vpoEN','vpoIN','pIP10','pMP2','aPN1_like',all.P1.type) & !is.na(pre_cachero.type) ~ pre_cachero.type,
      TRUE ~ pre_type
    ),
    post_type = case_when(
      !post_type %in% c('vPN1','aPN1','vpoEN','vpoIN','pIP10','pMP2','aPN1_like',all.P1.type) & !is.na(post_cachero.type) ~ post_cachero.type,
      TRUE ~ post_type
    )
  ) %>%
  mutate(
    pre_type = case_when(
      str_detect(pre_type, "TN1a") ~ "TN1a",
      str_detect(pre_type, "vPR9") ~ "vPR9",
      TRUE ~ pre_type
    ),
    post_type = case_when(
      str_detect(post_type, "TN1a") ~ "TN1a",
      str_detect(post_type, "vPR9") ~ "vPR9",
      TRUE ~ post_type
    )
  ) %>%
  mutate(
    pre_type = case_when(
      str_sub(pre_type, 1, 4) %in% c("SNpp", "SNch", "SNta", "SNxx") ~ str_sub(pre_type, 1, 4),
      TRUE ~ pre_type
    ),
    post_type = case_when(
      str_sub(post_type, 1, 4) %in% c("SNpp", "SNch", "SNta", "SNxx") ~ str_sub(post_type, 1, 4),
      TRUE ~ post_type
    )
  )

#conn.wo.gaba <- conn%>%filter(pre_nt!='gaba')


#nam <-calculate_normed_adj_matrix(conn.wo.gaba,cell.or.type='type',pre.or.post='avg') #avg
nam <-calculate_normed_adj_matrix(conn_work,cell.or.type='type',pre.or.post='avg') #avg
nam_thresholded <-nam

g.prout.mcns <- graph_from_adjacency_matrix(
  nam_thresholded,
  mode = "directed",
  weighted = TRUE,
  diag = FALSE
)
```


path finding new


```{r}

# Define parameters for path search
n_paths <-  3       # Number of strongest paths to find for each start-target pair
diversity <- 'otheredges'  # othernodes,otheredges,none

cell_types <- c('aPN1','vPN1','JO-B') #only JO-B
target_cells <- c("vpoEN",'CB1385','CB1385')  # List of target cells
target_cells <- c(target_cells,'pMP2')
target_cells <- c(target_cells,mba%>% filter(grepl('aSP-k',synonyms))%>%filter(!is.na(type))%>%pull(type)%>%unique())
target_cells <- c(target_cells,'vPN1','aPN1','aPN1_like','vpoEN','vpoIN','pIP10','pMP2','aSP-k','pIP-e')


# Transform weights using log
E(g.prout.mcns)$log_weight <- -log(E(g.prout.mcns)$weight)  # Negate to convert to shortest path problem



# Initialize an empty list to store results and a vector for important nodes
results <- list()
all_important_nodes <- character()

# Loop over all start (cell_types) and target (target_cells) pairs
for (start in cell_types) {
  for (end in target_cells) {

    # Only process if both start and end exist in the graph
    if ((start %in% V(g.prout.mcns)$name) && (end %in% V(g.prout.mcns)$name)) {

      # Make a copy of the graph to modify iteratively
      g_temp <- g.prout.mcns
      
      # List to hold all paths for this start–end pair
      pair_paths <- list()
      
      # Find up to 'n_paths' for the given pair
      for (i in 1:n_paths) {
        # Compute shortest path (using negative log weights so that lower is stronger)
        path_result <- shortest_paths(g_temp, from = start, to = end,
                                      weights = E(g_temp)$log_weight,
                                      output = "both")
        
        # Check if a path was found
        if (length(path_result$vpath[[1]]) > 0) {
          path_nodes <- path_result$vpath[[1]]
          path_edges <- path_result$epath[[1]]
          # Convert back to strength: reverse the -log transform
          final_strength <- exp(-sum(E(g_temp)[path_edges]$log_weight))
          
          # Save the results; note that we display the path using the names from the original graph
          pair_paths[[paste0("path", i)]] <- list(
            start = start,
            end = end,
            path = paste(V(g.prout.mcns)[path_nodes]$name, collapse = " -> "),
            strength = final_strength
          )
          # Collect nodes from this path into the overall list
          all_important_nodes <- c(all_important_nodes, V(g.prout.mcns)[path_nodes]$name)
          
          # Modify the temporary graph to seek a different path next time
          if (diversity=='othernodes') {
            # Remove intermediate nodes (all nodes except the start and end)
            intermediate_nodes <- V(g.prout.mcns)[path_nodes]$name  # get names from the original graph
            nodes_to_remove <- setdiff(intermediate_nodes, c(start, end))
            if (length(nodes_to_remove) > 0) {
              g_temp <- delete_vertices(g_temp, nodes_to_remove)
            }
          } else if(diversity=='otheredges'){
            # Remove the edges used in this path so that the next path will be different
            g_temp <- delete_edges(g_temp, path_edges)
          }else{
            1+1
          }
            
        } else {
          # If no further path is found, break out of the inner loop
          break
        }
      }
      # Save all the paths found for this start–end pair into the results list
      results[[paste(start, end, sep = "->")]] <- pair_paths
    } else {
      # If either node doesn't exist, store an NA entry for this pair
      results[[paste(start, end, sep = "->")]] <- list(list(
        start = start,
        end = end,
        path = NA,
        strength = NA
      ))
    }
  }
}

# Flatten the nested results list into a single data frame for easier inspection:
results_df <- do.call(rbind, lapply(results, function(pair_list) {
  do.call(rbind, lapply(pair_list, function(r) {
    data.frame(
      start = r$start,
      end = r$end,
      path = r$path,
      strength = r$strength,
      stringsAsFactors = FALSE
    )
  }))
}))

# (Optional) Get unique important nodes encountered in all the paths:
all_important_nodes <- unique(all_important_nodes)
results_df_wo_na <- results_df%>%
  filter(!is.na(strength))
# Look at the results
print(results_df_wo_na)
```






Open graph in RCy3

```{r}
library(RCy3)
library(dplyr)
library(stringr)

# Define nodes of interest
nodes_to_keep <- c("JO-B", "JO-B", "CB1078", "CB1542", "CB2108", "CB1383", "CB1066,CB3649",
                   "CB2364", "CB3382", "PVLP033", "CB3162", "CB3382", "vpoEN", "SIP124m",
                   "AVLP721m", "AVLP299_c", "DNp55", "CB1385", "AVLP711m", "SIP108m", 
                   "SIP120m", "SIP116m", "SIP114m", "PVLP211m", "pMP2", "AVLP744m")

in.plots <- c("vPN1", "aPN1", "aPN1_like", "vpoEN", "vpoIN", "pIP10", "pMP2", "JO-B")
P1_2_add <- conn_work%>%
  filter(pre_type %in% nodes_to_keep,
         grepl("^P1_", post_type))%>%
  pull(post_type)%>%
  unique()


nodes_to_keep <- c(unique(all_important_nodes), in.plots,P1_2_add)
nodes_to_keep <- c(unique(all_important_nodes))
nodes_to_keep <- c('pMP2','aPN1_like','pIP10','aIP-g','aDT-e','pIP-e','vpoEN','aPN1','P1_14a','JO-B','WED118','aDT-g','aSP-a','aSP-k','vpoIN','vPN1')



#nodes_to_keep <- c(nodes_to_keep,conn%>%filter(post_type=='IN06B003')%>%filter(grepl('SN',pre_type))%>%pull(pre_type)%>%unique())
#nodes_to_keep <- c(nodes_to_keep,mba%>%filter(grepl('TN1a',type))%>%pull(type)%>%unique())
#nodes_to_keep <- c(nodes_to_keep,in.plots,mba%>%filter(grepl('vPR9',type))%>%pull(type)%>%unique())



# Subset the graph
g.sub.prout.mcns <- induced_subgraph(g.prout.mcns, vids = V(g.prout.mcns)[name %in% nodes_to_keep])

# Shortest path distances from start_types
node_names <- V(g.sub.prout.mcns)$name
distance_to_start <- shortest.paths(g.sub.prout.mcns, to = V(g.sub.prout.mcns)[name %in% cell_types], weights = NA)
V(g.sub.prout.mcns)$distance_to_start <- ifelse(node_names %in% cell_types, 0, as.integer(distance_to_start))

# FRU/DSX metadata
try(fru_dsx_values <- conn_work %>%
      group_by(pre_type, post_type) %>%
      mutate(pre_fru_dsx = !is.na(pre_fru_dsx),
             post_fru_dsx = !is.na(post_fru_dsx)) %>%
      summarize(pre_fru_dsx = first(pre_fru_dsx),
                post_fru_dsx = first(post_fru_dsx)) %>%
      ungroup() %>%
      pivot_longer(cols = c(pre_fru_dsx, post_fru_dsx, pre_type, post_type),
                   names_to = c("side", ".value"), names_sep = "_") %>%
      select(-side) %>% distinct())

# NT metadata
nt_values <- conn_work %>%
  group_by(pre_type, post_type) %>%
  mutate(pre_nt = first(pre_nt),
         post_nt = first(post_nt)) %>%
  summarize(pre_nt = first(pre_nt),
            post_nt = first(post_nt)) %>%
  ungroup() %>%
  pivot_longer(cols = c(pre_nt, post_nt, pre_type, post_type),
               names_to = c("side", ".value"), names_sep = "_") %>%
  select(-side) %>% distinct()

# Match metadata to vertices
try(nt_for_vertices <- nt_values$nt[match(V(g.sub.prout.mcns)$name, nt_values$type)])
try(fru_dsx_for_vertices <- fru_dsx_values$fru[match(V(g.sub.prout.mcns)$name, fru_dsx_values$type)])
V(g.sub.prout.mcns)$nt <- nt_for_vertices
try(V(g.sub.prout.mcns)$fru_dsx <- fru_dsx_for_vertices)

# P1-P1 flag
el <- as_edgelist(g.sub.prout.mcns)
is_p1p1 <- grepl("^P1_", el[, 1])
E(g.sub.prout.mcns)$is_p1_p1 <- is_p1p1

# Scale weights
E(g.sub.prout.mcns)$weight <- E(g.sub.prout.mcns)$weight * 100

# --- Dynamic quantile-based binning for weights > 1 ---
weights_all <- E(g.sub.prout.mcns)$weight
weights_above_1 <- weights_all[weights_all > 1]

# Compute quantiles and round nicely for legend clarity
quantile_breaks <- quantile(weights_above_1, probs = c(0, 0.25, 0.5, 0.75, 1), na.rm = TRUE)
rounded_breaks <- unique(round(quantile_breaks,2))  # ensure no duplicated breaks

# Handle edge case: fewer than 5 unique bins
if (length(rounded_breaks) < 5) {
  rounded_breaks <- pretty(weights_above_1, n = 4)
}

# Assign bin index
E(g.sub.prout.mcns)$arrow_class <- cut(
  weights_all,
  breaks = rounded_breaks,
  include.lowest = TRUE,
  labels = FALSE
)

# Optional: create human-readable bin label
labels <- paste(head(rounded_breaks, -1), tail(rounded_breaks, -1), sep = "–")
E(g.sub.prout.mcns)$arrow_class_label <- labels[E(g.sub.prout.mcns)$arrow_class]

# Assign 0 and "0" for weights <= 1
E(g.sub.prout.mcns)$arrow_class[weights_all <= 1] <- 0
E(g.sub.prout.mcns)$arrow_class_label[weights_all <= 1] <- "≤1"

# Create network in Cytoscape
RCy3::createNetworkFromIgraph(g.sub.prout.mcns)
```


```{r}
# Plot kernel density estimate in base R
d <- density(weights_above_1)
plot(d, main = "KDE Plot of Weights", xlab = "Weight", ylab = "Density")
```