---
title: "graph_based_explore"
output: html_document
---

load dependencies

```{r}
fafbseg::flywire_connectome_data("syn")
library(malecns)
library(coconatfly)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(stringr)
library(igraph)
library(fafbseg)
library(tidygraph)
library(ggraph)
synapse_threshold=5
mba<-mcns_body_annotations()
mba.type.coalesced <-  mba %>%
  mutate(type = coalesce(type, 
                         flywire_type, 
                         hemibrain_type, 
                         manc_type))
flytable<-flytable_query("select * from info")
```

Create a graph of 4 layers and then find the strongest path from sink to sink


Create graph for malecns and weighted
```{r}
#cells
cell_types <- c('CB1076','CB1078', 'CB3710', 'CB2521','CB1542', 'CB1038', 'CB1427', 'CB2556', 'CB2380')


#level 1

level1.poin.mcns.output <- cf_partner_summary(cf_ids(malecns = mba.type.coalesced %>% 
                                             filter(flywire_type %in% cell_types)%>%
                                             pull(bodyid)), 
                                          partners = 'out', 
                                          threshold = synapse_threshold,
                                          normalise = F,
                                          aggregate.query=T)%>%
  filter(!is.na(type.post))


level1.poin.mcns.post.input <- cf_partners(cf_ids(malecns = mba.type.coalesced %>% 
                                             filter(flywire_type %in% level1.poin.mcns.output$type.post)%>%
                                             pull(bodyid)), 
                                          partners = 'in', 
                                          threshold = synapse_threshold)%>%
  left_join(mba.type.coalesced%>%
              select(bodyid,type)%>%
              rename('post_type'='type'),
            by='bodyid')%>%
  group_by(post_type)%>%
  summarize(syn.post=sum(weight))

level1.poin.mcns.output.normed <- level1.poin.mcns.output%>%
  left_join(level1.poin.mcns.post.input,by=c('type.post'='post_type'))%>%
  mutate(weight=weight/syn.post)


#level 2




level2.poin.mcns.output <- cf_partner_summary(cf_ids(malecns= mba.type.coalesced %>% 
                                             filter(flywire_type %in% level1.poin.mcns.output$type.post)%>%
                                             pull(bodyid)), 
                                          partners = 'out', 
                                          threshold = synapse_threshold,
                                          normalise = F,
                                          aggregate.query=T)%>%
  filter(!is.na(type.post))


level2.poin.mcns.post.input  <- cf_partners(cf_ids(malecns= mba.type.coalesced %>% 
                                             filter(type %in% (level2.poin.mcns.output%>%
                                                                 pull(type.post)%>%
                                                                 unique()))%>%
                                             pull(bodyid)), 
                                          partners = 'in', 
                                          threshold = synapse_threshold)%>%
  left_join(mba.type.coalesced%>%
              select(bodyid,type)%>%
              rename('post_type'='type'),
            by='bodyid')%>%
  group_by(post_type)%>%
  summarize(syn.post=sum(weight))

level2.poin.mcns.output.normed<- level2.poin.mcns.output%>%
  left_join(level2.poin.mcns.post.input,by=c('type.post'='post_type'))%>%
  mutate(weight=weight/syn.post)


#level3.poin.mcns




level3.poin.mcns.output <- cf_partner_summary(cf_ids(malecns= mba.type.coalesced %>% 
                                             filter(type %in% level2.poin.mcns.output$type.post)%>%
                                             pull(bodyid)), 
                                          partners = 'out', 
                                          threshold = synapse_threshold,
                                          normalise = F,
                                          aggregate.query=T)%>%
  filter(!is.na(type.post))


level3.poin.mcns.post.input  <- cf_partners(cf_ids(malecns= mba.type.coalesced %>% 
                                             filter(type %in% (level3.poin.mcns.output%>%
                                                                 pull(type.post)%>%
                                                                 unique()))%>%
                                             pull(bodyid)), 
                                          partners = 'in', 
                                          threshold = synapse_threshold)%>%
  left_join(mba.type.coalesced%>%
              select(bodyid,type)%>%
              rename('post_type'='type'),
            by='bodyid')%>%
  group_by(post_type)%>%
  summarize(syn.post=sum(weight))

level3.poin.mcns.output.normed<- level3.poin.mcns.output%>%
  left_join(level3.poin.mcns.post.input,by=c('type.post'='post_type'))%>%
  mutate(weight=weight/syn.post)



all.levels.poin.mcns.output <- rbind(level1.poin.mcns.output.normed,level2.poin.mcns.output.normed,level3.poin.mcns.output.normed) %>%distinct()

g.poin.mcns <- graph_from_data_frame(all.levels.poin.mcns.output%>%
                             select(type.pre,
                                    type.post,
                                    weight),
                           directed = TRUE)


```

Solve to find the best path (maximum product path problem)

```{r}
library(ggplot2)
library(reshape2)

# Your existing code
cell_types <- c('CB1076','CB1078', 'CB3710', 'CB2521','CB1542', 'CB1038', 'CB1427', 'CB2556a', 'CB2380')
target_cells <- c("vpoEN", "AVLP721m",'CB1385')  # List of target cells
target_cells <- c(V(g.poin.mcns)$name[grepl("P1_", V(g.poin.mcns)$name)], target_cells)
target_cells <- c(mba%>% filter(grepl('aSP-k',synonyms))%>%filter(!is.na(type))%>%pull(type)%>%unique(),target_cells)

# Transform weights using log
E(g.poin.mcns)$log_weight <- -log(E(g.poin.mcns)$weight)  # Negate to convert to shortest path problem

# Initialize an empty list to store results
results <- list()

# Run shortest path calculations
for (start in cell_types) {
  for (end in target_cells) {
    # Find shortest (strongest) path using Dijkstra
    path <- shortest_paths(g.poin.mcns, from = start, to = end, weights = E(g.poin.mcns)$log_weight, output = "both")
    
    # Extract path and compute final strength
    if (length(path$vpath[[1]]) > 0) {  # Check if a valid path exists
      path_nodes <- path$vpath[[1]]  # Path nodes
      path_edges <- path$epath[[1]]  # Path edges
      final_strength <- exp(-sum(E(g.poin.mcns)[path_edges]$log_weight))  # Convert back

      # Store results
      results[[paste(start, end, sep = "->")]] <- list(
        start = start,
        end = end,
        path = paste(V(g.poin.mcns)[path_nodes]$name, collapse = " -> "),
        strength = final_strength
      )
    } else {
      # If no path exists, store NA
      results[[paste(start, end, sep = "->")]] <- list(path = NA, strength = NA)
    }
  }
}

# Convert results to a data frame
results_df <- do.call(rbind, lapply(names(results), function(x) {
  data.frame(
    start = results[[x]]$start, 
    end = results[[x]]$end,
    path = results[[x]]$path, 
    strength = results[[x]]$strength, 
    stringsAsFactors = FALSE
  )
}))

# View results in a readable format

# Create a matrix for heatmap
heatmap_matrix <- matrix(NA, nrow = length(cell_types), ncol = length(target_cells))
rownames(heatmap_matrix) <- cell_types
colnames(heatmap_matrix) <- target_cells

# Fill the matrix with path strengths
for (i in 1:nrow(results_df)) {
  start <- results_df$start[i]
  end <- results_df$end[i]
  strength <- results_df$strength[i]
  heatmap_matrix[start, end] <- strength
}

# Convert matrix to a data frame for ggplot2
heatmap_df <- melt(heatmap_matrix, varnames = c("Start", "End"), value.name = "Strength")

# Plot heatmap using ggplot2
library(pheatmap)
heatmap_matrix[is.na(heatmap_matrix)] <- 0

# Plot heatmap using pheatmap with log scale
pheatmap(heatmap_matrix, cluster_rows = T, cluster_cols = T, display_numbers = F,fontsize_col = 8,angle_col=90)



```

Total effectiveness


```{r}


cell_types <- c('CB1076','CB1078', 'CB3710', 'CB2521','CB1542', 'CB1038', 'CB1427', 'CB2556a', 'CB2380')
target_cells <- c("vpoEN", "AVLP721m",'CB1385')  # List of target cells
target_cells <- c(V(g.poin.mcns)$name[grepl("P1_", V(g.poin.mcns)$name)], target_cells)
target_cells <- c(mba%>% filter(grepl('aSP-k',synonyms))%>%filter(!is.na(type))%>%pull(type)%>%unique(),target_cells)

# Transform weights using log
E(g.poin.mcns)$log_weight <- -log(E(g.poin.mcns)$weight)  # Negate to convert to shortest path problem

# Initialize an empty list to store results
results <- list()

# Run shortest path calculations
for (start in cell_types) {
  for (end in target_cells) {
    # Find all paths between start and end
    all_paths <- all_shortest_paths(g.poin.mcns, from = start, to = end, weights = E(g.poin.mcns)$log_weight)

    # Sum the strength of each path
    total_strength <- 0
    if (length(all_paths$vpath) > 0) {  # Check if there are valid paths
      for (path in all_paths$vpath) {
        path_edges <- get.edges(g.poin.mcns, path)  # Extract edges for this path
        total_strength <- total_strength + exp(-sum(E(g.poin.mcns)[path_edges]$log_weight))  # Add strength of this path
      }
    }else {
      # If no path exists, store NA
      total_strength<- 0
    }

    # Store results
    results[[paste(start, end, sep = "->")]] <- list(
      start = start,
      end = end,
      path_count = length(all_paths$vpath),  # Number of paths
      total_strength = total_strength
    )
  }
}

# Convert results to a data frame
results_df <- do.call(rbind, lapply(names(results), function(x) {
  data.frame(
    start = results[[x]]$start, 
    end = results[[x]]$end,
    path_count = results[[x]]$path_count,  # Add path count
    total_strength = results[[x]]$total_strength, 
    stringsAsFactors = FALSE
  )
}))

# View results in a readable format

# Create a matrix for heatmap
heatmap_matrix <- matrix(NA, nrow = length(cell_types), ncol = length(target_cells))
rownames(heatmap_matrix) <- cell_types
colnames(heatmap_matrix) <- target_cells

# Fill the matrix with total strengths
for (i in 1:nrow(results_df)) {
  start <- results_df$start[i]
  end <- results_df$end[i]
  total_strength <- results_df$total_strength[i]
  heatmap_matrix[start, end] <- total_strength
}

# Convert matrix to a data frame for ggplot2
heatmap_df <- melt(heatmap_matrix, varnames = c("Start", "End"), value.name = "Total Strength")

# Plot heatmap using ggplot2
library(pheatmap)
heatmap_matrix[is.na(heatmap_matrix)] <- 0

# Plot heatmap using pheatmap
pheatmap(heatmap_matrix, cluster_rows = T, cluster_cols = T, display_numbers = F, fontsize_col = 8, angle_col = 90)
```






